CC = gcc
CFLAGS = -I include -Wall -Wextra
SRC = src/main.c src/fcfs.c src/sjf.c src/priority.c src/round_robin.c src/utils.c
OUT = scheduler

all: $(SRC)
	$(CC) $(SRC) $(CFLAGS) -o $(OUT)

clean:
	rm -f $(OUT)
